from sqlalchemy import Column, Integer, String, Date, Float, Boolean
from app.core.database import Base


class PhilipSnatKhlGame(Base):
    __tablename__ = "philip_snat_khl_games"

    id = Column(Integer, primary_key=True, index=True)
    khl_id = Column(Integer, index=True, nullable=False)
    date = Column(Date, nullable=False)
    hour = Column(String, nullable=True)
    home_team = Column(String, nullable=False)
    away_team = Column(String, nullable=False)
    winner = Column(String, nullable=True)
    home_score = Column(Float, nullable=True)
    away_score = Column(Float, nullable=True)
    home_score_no_ot = Column(Float, nullable=True)
    away_score_no_ot = Column(Float, nullable=True)
    total_score = Column(Float, nullable=True)
    total_score_no_ot = Column(Float, nullable=True)
    ot = Column(Boolean, nullable=True)
    so = Column(Boolean, nullable=True)

    h_rank = Column(Integer, nullable=True)
    a_rank = Column(Integer, nullable=True)
    rank_diff = Column(Integer, nullable=True)
    h_gpg = Column(Float, nullable=True)
    a_gpg = Column(Float, nullable=True)
    gpg_diff = Column(Float, nullable=True)
    h_pk_pct = Column(String, nullable=True)
    a_pk_pct = Column(String, nullable=True)
    pk_pct_diff = Column(Float, nullable=True)
    h_pm_pg = Column(String, nullable=True)
    a_pm_pg = Column(String, nullable=True)
    pm_pg_diff = Column(Float, nullable=True)
    h_pp_pct = Column(String, nullable=True)
    a_pp_pct = Column(String, nullable=True)
    pp_pct_diff = Column(Float, nullable=True)
    h_ppg_apg = Column(Float, nullable=True)
    a_ppg_apg = Column(Float, nullable=True)
    ppg_apg_diff = Column(Float, nullable=True)
    h_sv_pct = Column(String, nullable=True)
    a_sv_pct = Column(String, nullable=True)
    sv_pct_diff = Column(Float, nullable=True)
    h_svpg = Column(Float, nullable=True)
    a_svpg = Column(Float, nullable=True)
    svpg_diff = Column(Float, nullable=True)
    h_spg = Column(Float, nullable=True)
    a_spg = Column(Float, nullable=True)
    spg_diff = Column(Float, nullable=True)
    h_lgd = Column(String, nullable=True)
    a_lgd = Column(String, nullable=True)
    h_lgpa = Column(String, nullable=True)
    a_lgpa = Column(String, nullable=True)
    h_lgop = Column(String, nullable=True)
    a_lgop = Column(String, nullable=True)
    lgop_diff = Column(Integer, nullable=True)
    h_l5gw = Column(Integer, nullable=True)
    a_l5gw = Column(Integer, nullable=True)
    l5gw_diff = Column(Integer, nullable=True)
    hom_score_no_ot = Column(Float, nullable=True)
