from sqlalchemy import Column, Integer, String, Date, Float, Boolean, JSON
from app.core.database import Base


class PhilipSnatShlGame(Base):
    __tablename__ = "philip_snat_shl_games"

    id = Column(Integer, primary_key=True, index=True)
    shl_uuid = Column(String, index=True, nullable=False)
    date = Column(Date, nullable=False)
    home_team = Column(String, nullable=False)
    away_team = Column(String, nullable=False)
    winner = Column(Integer, nullable=True)
    home_score = Column(Integer, nullable=True)
    away_score = Column(Integer, nullable=True)
    home_score_no_ot = Column(Integer, nullable=True)
    away_score_no_ot = Column(Integer, nullable=True)
    total_goals = Column(Integer, nullable=True)
    total_goals_no_ot = Column(Integer, nullable=True)
    ot = Column(Boolean, nullable=True)
    so = Column(Boolean, nullable=True)

    home_rank = Column(Integer, nullable=True)
    away_rank = Column(Integer, nullable=True)
    rank_diff = Column(Integer, nullable=True)
    h_gpg = Column(Float, nullable=True)
    a_gpg = Column(Float, nullable=True)
    gpg_diff = Column(Float, nullable=True)
    gpmutual = Column(Float, nullable=True)
    h_gapg = Column(Float, nullable=True)
    a_gapg = Column(Float, nullable=True)
    gapg_diff = Column(Float, nullable=True)
    gapmutual = Column(Float, nullable=True)
    h_pp_perc = Column(Float, nullable=True)
    a_pp_perc = Column(Float, nullable=True)
    h_pk_perc = Column(Float, nullable=True)
    a_pk_perc = Column(Float, nullable=True)
    h_s_eff = Column(Float, nullable=True)
    a_s_eff = Column(Float, nullable=True)
    h_svs_perc = Column(Float, nullable=True)
    a_svs_perc = Column(Float, nullable=True)
    h_fo_perc = Column(Float, nullable=True)
    a_fo_perc = Column(Float, nullable=True)
    h_cf_perc = Column(Float, nullable=True)
    a_cf_perc = Column(Float, nullable=True)
    h_ff_perc = Column(Float, nullable=True)
    a_ff_perc = Column(Float, nullable=True)
    h_close_cf_perc = Column(Float, nullable=True)
    a_close_cf_perc = Column(Float, nullable=True)
    h_close_ff_perc = Column(Float, nullable=True)
    a_close_ff_perc = Column(Float, nullable=True)
    h_pdo = Column(Float, nullable=True)
    a_pdo = Column(Float, nullable=True)
    h_st_perc = Column(Float, nullable=True)
    a_st_perc = Column(Float, nullable=True)
    h_pps_eff = Column(Float, nullable=True)
    a_pps_eff = Column(Float, nullable=True)
    h_sogpg = Column(Float, nullable=True)
    a_sogpg = Column(Float, nullable=True)
    sogpg_diff = Column(Float, nullable=True)
    sogpg_mutual = Column(Float, nullable=True)
    h_l5gw = Column(Integer, nullable=True)
    a_l5gw = Column(Integer, nullable=True)
    l5gw_diff = Column(Integer, nullable=True)
    h_lmd_gpg1 = Column(Float, nullable=True)
    a_lmd_gpg1 = Column(Float, nullable=True)
    h_lmd_gpg2 = Column(Float, nullable=True)
    a_lmd_gpg2 = Column(Float, nullable=True)
    h_lmd_gapg1 = Column(Float, nullable=True)
    a_lmd_gapg1 = Column(Float, nullable=True)
    h_lmd_gapg2 = Column(Float, nullable=True)
    a_lmd_gapg2 = Column(Float, nullable=True)
    h_shame_factor = Column(Float, nullable=True)
    a_shame_factor = Column(Float, nullable=True)
    h_hunger_fg = Column(Float, nullable=True)
    a_hunger_fg = Column(Float, nullable=True)
    hunger_fg_diff = Column(Float, nullable=True)
    hunger_fg_mutual = Column(Float, nullable=True)
    prediction_winner = Column(Float, nullable=True)
    prediction_goals = Column(JSON, nullable=True)
