from sqlalchemy import Column, Integer, String, Date, Float, Boolean, JSON
from app.core.database import Base


class PhilipSnatNlGame(Base):
    __tablename__ = "philip_snat_nl_games"

    id = Column(Integer, primary_key=True, index=True)
    nl_id = Column(String, index=True, nullable=False)
    date = Column(Date, nullable=False)
    hour = Column(String, nullable=True)
    home_team = Column(String, nullable=False)
    away_team = Column(String, nullable=False)
    winner = Column(String, nullable=True)
    home_score = Column(Float, nullable=True)
    away_score = Column(Float, nullable=True)
    home_score_no_ot = Column(Float, nullable=True)
    away_score_no_ot = Column(Float, nullable=True)
    total_score = Column(Float, nullable=True)
    total_score_no_ot = Column(Float, nullable=True)
    ot = Column(Boolean, nullable=True)
    so = Column(Boolean, nullable=True)

    h_rank = Column(Integer, nullable=True)
    a_rank = Column(Integer, nullable=True)
    rank_diff = Column(Integer, nullable=True)
    h_gpg = Column(Float, nullable=True)
    a_gpg = Column(Float, nullable=True)
    gpg_diff = Column(Float, nullable=True)
    h_gapg = Column(Float, nullable=True)
    a_gapg = Column(Float, nullable=True)
    gapg_diff = Column(Float, nullable=True)
    h_sogpg = Column(Float, nullable=True)
    a_sogpg = Column(Float, nullable=True)
    sogpg_diff = Column(Float, nullable=True)
    h_sslotpg = Column(Float, nullable=True)
    a_sslotpg = Column(Float, nullable=True)
    sslotpg_diff = Column(Float, nullable=True)
    h_shmpg = Column(Float, nullable=True)
    a_shmpg = Column(Float, nullable=True)
    hmpg_diff = Column(Float, nullable=True)
    h_shppg = Column(Float, nullable=True)
    a_shppg = Column(Float, nullable=True)
    hpppg_diff = Column(Float, nullable=True)
    h_ppgpgg = Column(Float, nullable=True)
    a_ppgpgg = Column(Float, nullable=True)
    ppgpgg_diff = Column(Float, nullable=True)
    h_ppgapg = Column(Float, nullable=True)
    a_ppgapg = Column(Float, nullable=True)
    ppgapg_diff = Column(Float, nullable=True)
    h_ppgeff = Column(Float, nullable=True)
    a_ppgeff = Column(Float, nullable=True)
    ppgeff_diff = Column(Float, nullable=True)
    h_pkeff = Column(Float, nullable=True)
    a_pkeff = Column(Float, nullable=True)
    pkeff_diff = Column(Float, nullable=True)
    h_sapg = Column(Float, nullable=True)
    a_sapg = Column(Float, nullable=True)
    sapg_diff = Column(Float, nullable=True)
    h_sslotapg = Column(Float, nullable=True)
    a_sslotapg = Column(Float, nullable=True)
    sslotapg_diff = Column(Float, nullable=True)
    h_lgd = Column(String, nullable=True)
    a_lgd = Column(String, nullable=True)
    h_lgpa = Column(String, nullable=True)
    a_lgpa = Column(String, nullable=True)
    h_lgop = Column(String, nullable=True)
    a_lgop = Column(String, nullable=True)
    lgop_diff = Column(Integer, nullable=True)
    h_l5gw = Column(Integer, nullable=True)
    a_l5gw = Column(Integer, nullable=True)
    l5gw_diff = Column(Integer, nullable=True)
    prediction_winner = Column(Float, nullable=True)
    prediction_goals = Column(JSON, nullable=True)
