from sqlalchemy import Column, Integer, String, Date, SmallInteger, Float, Boolean
from sqlalchemy.orm import relationship
from app.core.database import Base


class PhilipSnatNhlGame(Base):
    __tablename__ = "philip_snat_nhl_games"

    id = Column(Integer, primary_key=True, index=True)
    nhl_id = Column(Integer, index=True)
    date = Column(Date, nullable=False)
    home_team = Column(String, nullable=False)
    away_team = Column(String, nullable=False)
    winner = Column(SmallInteger, nullable=True)
    home_goals_no_ot = Column(Integer, nullable=True)
    away_goals_no_ot = Column(Integer, nullable=True)
    total_goals_no_ot = Column(Integer, nullable=True)
    home_standing = Column(Integer, nullable=False)
    away_standing = Column(Integer, nullable=False)
    diff_standing = Column(Integer, nullable=False)

    home_gpg = Column(Float, nullable=False)
    away_gpg = Column(Float, nullable=False)
    mutual_gpg = Column(Integer, nullable=False)
    diff_gpg = Column(Float, nullable=False)
    home_gpga = Column(Float, nullable=False)
    away_gpga = Column(Float, nullable=False)
    diff_gpga = Column(Float, nullable=False)
    home_sv = Column(Float, nullable=False)
    away_sv = Column(Float, nullable=False)
    diff_sv = Column(Float, nullable=False)
    home_lgd = Column(SmallInteger, nullable=False)
    away_lgd = Column(SmallInteger, nullable=False)
    home_lgpa = Column(SmallInteger, nullable=False)
    away_lgpa = Column(SmallInteger, nullable=False)
    home_lgop = Column(Integer, nullable=False)
    away_lgop = Column(Integer, nullable=False)
    home_shame_factor = Column(Float, nullable=False)
    away_shame_factor = Column(Float, nullable=False)
    outcome_shame_factor = Column(Float, nullable=False)
    home_l5gw = Column(Integer, nullable=False)
    away_l5gw = Column(Integer, nullable=False)
    diff_l5gw = Column(Integer, nullable=False)
    home_dflg = Column(Integer, nullable=False)
    away_dflg = Column(Integer, nullable=False)
    home_lgot = Column(Boolean, nullable=False)
    away_lgot = Column(Boolean, nullable=False)
    home_lgso = Column(Boolean, nullable=False)
    away_lgso = Column(Boolean, nullable=False)
    home_lmd1 = Column(Integer, nullable=False)
    away_lmd1 = Column(Integer, nullable=False)
    lmd1_mutual = Column(Integer, nullable=False)
    home_lmd2 = Column(Integer, nullable=False)
    away_lmd2 = Column(Integer, nullable=False)
    home_spg = Column(Integer, nullable=False)
    away_spg = Column(Integer, nullable=False)
    home_spga = Column(Integer, nullable=False)
    away_spga = Column(Integer, nullable=False)
    hunger_fg = Column(Integer, nullable=False)
    home_fatigue = Column(Integer, nullable=False)
    away_fatigue = Column(Integer, nullable=False)
