"""Redone database schema

Revision ID: 104ea7c765da
Revises: 467f528161b5
Create Date: 2025-12-28 21:25:57.860976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104ea7c765da'
down_revision = '467f528161b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM types first using raw SQL
    op.execute("CREATE TYPE betresult AS ENUM ('WIN', 'LOOSE', 'TO_RESOLVE')")
    op.execute("CREATE TYPE gamestatus AS ENUM ('PENDING', 'FINISHED')")
    op.execute("CREATE TYPE gamewinner AS ENUM ('HOME', 'AWAY')")

    op.create_table('tipster_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipster_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipster_id'], ['tipsters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipster_tiers_id'), 'tipster_tiers', ['id'], unique=False)
    op.add_column('bet_events', sa.Column('result', sa.Enum('WIN', 'LOOSE', 'TO_RESOLVE', name='betresult', create_type=False), nullable=True))
    op.add_column('bet_recommendations', sa.Column('tipster_tier_id', sa.Integer(), nullable=True))
    op.add_column('bet_recommendations', sa.Column('tipster_description', sa.String(length=1000), nullable=True))
    op.add_column('bet_recommendations', sa.Column('stake', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_foreign_key(None, 'bet_recommendations', 'tipster_tiers', ['tipster_tier_id'], ['id'])
    op.add_column('games', sa.Column('status', sa.Enum('PENDING', 'FINISHED', name='gamestatus', create_type=False), nullable=True))
    op.add_column('games', sa.Column('winner', sa.Enum('HOME', 'AWAY', name='gamewinner', create_type=False), nullable=True))
    op.add_column('games', sa.Column('home_team_score', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_team_score', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('overtime', sa.Boolean(), nullable=True))
    op.add_column('games', sa.Column('shootout', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'shootout')
    op.drop_column('games', 'overtime')
    op.drop_column('games', 'away_team_score')
    op.drop_column('games', 'home_team_score')
    op.drop_column('games', 'winner')
    op.drop_column('games', 'status')
    op.drop_constraint(None, 'bet_recommendations', type_='foreignkey')
    op.drop_column('bet_recommendations', 'stake')
    op.drop_column('bet_recommendations', 'tipster_description')
    op.drop_column('bet_recommendations', 'tipster_tier_id')
    op.drop_column('bet_events', 'result')
    op.drop_index(op.f('ix_tipster_tiers_id'), table_name='tipster_tiers')
    op.drop_table('tipster_tiers')

    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS gamewinner")
    op.execute("DROP TYPE IF EXISTS gamestatus")
    op.execute("DROP TYPE IF EXISTS betresult")
    # ### end Alembic commands ###
