"""add_sport_league_to_bet_events

Revision ID: 1653c7e806a4
Revises: a67cdf66fca9
Create Date: 2025-10-12 19:57:18.400762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1653c7e806a4'
down_revision = 'a67cdf66fca9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_events', sa.Column('sport_id', sa.Integer(), nullable=False))
    op.add_column('bet_events', sa.Column('league_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bet_events', 'leagues', ['league_id'], ['id'])
    op.create_foreign_key(None, 'bet_events', 'sports', ['sport_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bet_events', type_='foreignkey')
    op.drop_constraint(None, 'bet_events', type_='foreignkey')
    op.drop_column('bet_events', 'league_id')
    op.drop_column('bet_events', 'sport_id')
    # ### end Alembic commands ###
