"""add_unique_constraint_bet_recommendations

Revision ID: 249c78459e76
Revises: b30cfb4b3a93
Create Date: 2026-01-06 23:08:31.314869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249c78459e76'
down_revision = 'b30cfb4b3a93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tipster_bet_event_tier', 'bet_recommendations', ['tipster_id', 'bet_event_id', 'tipster_tier_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tipster_bet_event_tier', 'bet_recommendations', type_='unique')
    # ### end Alembic commands ###
