"""add_bet_event_table

Revision ID: 2af88833a948
Revises: 001_initial
Create Date: 2025-10-07 19:54:07.459013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af88833a948'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_events_id'), 'bet_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bet_events_id'), table_name='bet_events')
    op.drop_table('bet_events')
    # ### end Alembic commands ###
