"""update_philip_snat_nhl_games_nullable

Revision ID: 30f256561df8
Revises: 82cf571626ce
Create Date: 2026-02-24 18:07:11.390171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f256561df8'
down_revision = '82cf571626ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('philip_snat_nhl_games', 'winner',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('philip_snat_nhl_games', 'home_goals_no_ot',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('philip_snat_nhl_games', 'away_goals_no_ot',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('philip_snat_nhl_games', 'total_goals_no_ot',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('philip_snat_nhl_games', 'ai_predicted_winner',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('philip_snat_nhl_games', 'ai_predicted_home_goals',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('philip_snat_nhl_games', 'ai_predicted_away_goals',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('philip_snat_nhl_games', 'ai_predicted_total_goals',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('philip_snat_nhl_games', 'ai_predicted_total_goals',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('philip_snat_nhl_games', 'ai_predicted_away_goals',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('philip_snat_nhl_games', 'ai_predicted_home_goals',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('philip_snat_nhl_games', 'ai_predicted_winner',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('philip_snat_nhl_games', 'total_goals_no_ot',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('philip_snat_nhl_games', 'away_goals_no_ot',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('philip_snat_nhl_games', 'home_goals_no_ot',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('philip_snat_nhl_games', 'winner',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
