"""add_bet_event_table

Revision ID: 3269b4a604e3
Revises: dd7689c32a79
Create Date: 2025-10-07 20:23:01.310745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3269b4a604e3'
down_revision = 'dd7689c32a79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
