"""add_bet_event_table

Revision ID: 467f528161b5
Revises: 1653c7e806a4
Create Date: 2025-10-12 19:59:44.690797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467f528161b5'
down_revision = '1653c7e806a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bet_events_league_id_fkey', 'bet_events', type_='foreignkey')
    op.drop_constraint('bet_events_sport_id_fkey', 'bet_events', type_='foreignkey')
    op.drop_column('bet_events', 'sport_id')
    op.drop_column('bet_events', 'league_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_events', sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bet_events', sa.Column('sport_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('bet_events_sport_id_fkey', 'bet_events', 'sports', ['sport_id'], ['id'])
    op.create_foreign_key('bet_events_league_id_fkey', 'bet_events', 'leagues', ['league_id'], ['id'])
    # ### end Alembic commands ###
