"""add_bet_event_table

Revision ID: 4ed8a2082054
Revises: 3269b4a604e3
Create Date: 2025-10-07 20:24:59.254266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed8a2082054'
down_revision = '3269b4a604e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet_events', 'league')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_events', sa.Column('league', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
