"""add_bet_event_table

Revision ID: 5095d12c33a7
Revises: 7af32049632c
Create Date: 2025-10-12 12:48:16.175838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5095d12c33a7'
down_revision = '7af32049632c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('api_league_key', sa.String(), nullable=False))
    op.drop_column('leagues', 'api_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('api_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('leagues', 'api_league_key')
    # ### end Alembic commands ###
