"""update

Revision ID: 666cd16a0db6
Revises: c73c9b99a587
Create Date: 2025-10-12 13:59:31.730971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666cd16a0db6'
down_revision = 'c73c9b99a587'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('bookmaker', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'bookmaker')
    # ### end Alembic commands ###
