"""update

Revision ID: 681992e31d79
Revises: 666cd16a0db6
Create Date: 2025-10-12 14:01:14.314981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681992e31d79'
down_revision = '666cd16a0db6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'bookmaker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('bookmaker', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
