"""add_bet_event_table

Revision ID: 799928c99263
Revises: 35c04759724e
Create Date: 2025-10-08 16:52:23.493247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799928c99263'
down_revision = '35c04759724e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('api_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'api_id')
    # ### end Alembic commands ###
