"""add_bet_event_table

Revision ID: 7af32049632c
Revises: 799928c99263
Create Date: 2025-10-08 16:54:29.842905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af32049632c'
down_revision = '799928c99263'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('country_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'country_code')
    # ### end Alembic commands ###
