"""add_category_name_and_category_id_to_bet_events

Revision ID: 813a41fc29e7
Revises: 6619be03a9a4
Create Date: 2026-01-27 22:26:25.844035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813a41fc29e7'
down_revision = '6619be03a9a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_events', sa.Column('category_name', sa.String(), nullable=True))
    op.add_column('bet_events', sa.Column('category_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet_events', 'category_id')
    op.drop_column('bet_events', 'category_name')
    # ### end Alembic commands ###
