"""add_philip_snat_nhl_games

Revision ID: 82cf571626ce
Revises: bcd892d0d6cf
Create Date: 2026-02-24 18:04:41.136782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cf571626ce'
down_revision = 'bcd892d0d6cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('philip_snat_nhl_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhl_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('winner', sa.SmallInteger(), nullable=False),
    sa.Column('home_goals_no_ot', sa.Integer(), nullable=False),
    sa.Column('away_goals_no_ot', sa.Integer(), nullable=False),
    sa.Column('total_goals_no_ot', sa.Integer(), nullable=False),
    sa.Column('ai_predicted_winner', sa.SmallInteger(), nullable=False),
    sa.Column('ai_predicted_home_goals', sa.Integer(), nullable=False),
    sa.Column('ai_predicted_away_goals', sa.Integer(), nullable=False),
    sa.Column('ai_predicted_total_goals', sa.Integer(), nullable=False),
    sa.Column('home_standing', sa.Integer(), nullable=False),
    sa.Column('away_standing', sa.Integer(), nullable=False),
    sa.Column('diff_standing', sa.Integer(), nullable=False),
    sa.Column('home_gpg', sa.Float(), nullable=False),
    sa.Column('away_gpg', sa.Float(), nullable=False),
    sa.Column('mutual_gpg', sa.Integer(), nullable=False),
    sa.Column('diff_gpg', sa.Float(), nullable=False),
    sa.Column('home_gpga', sa.Float(), nullable=False),
    sa.Column('away_gpga', sa.Float(), nullable=False),
    sa.Column('diff_gpga', sa.Float(), nullable=False),
    sa.Column('home_sv', sa.Float(), nullable=False),
    sa.Column('away_sv', sa.Float(), nullable=False),
    sa.Column('diff_sv', sa.Float(), nullable=False),
    sa.Column('home_lgd', sa.SmallInteger(), nullable=False),
    sa.Column('away_lgd', sa.SmallInteger(), nullable=False),
    sa.Column('home_lgpa', sa.SmallInteger(), nullable=False),
    sa.Column('away_lgpa', sa.SmallInteger(), nullable=False),
    sa.Column('home_lgop', sa.Integer(), nullable=False),
    sa.Column('away_lgop', sa.Integer(), nullable=False),
    sa.Column('home_shame_factor', sa.Float(), nullable=False),
    sa.Column('away_shame_factor', sa.Float(), nullable=False),
    sa.Column('outcome_shame_factor', sa.Float(), nullable=False),
    sa.Column('home_l5gw', sa.Integer(), nullable=False),
    sa.Column('away_l5gw', sa.Integer(), nullable=False),
    sa.Column('diff_l5gw', sa.Integer(), nullable=False),
    sa.Column('home_dflg', sa.Integer(), nullable=False),
    sa.Column('away_dflg', sa.Integer(), nullable=False),
    sa.Column('home_lgot', sa.Boolean(), nullable=False),
    sa.Column('away_lgot', sa.Boolean(), nullable=False),
    sa.Column('home_lgso', sa.Boolean(), nullable=False),
    sa.Column('away_lgso', sa.Boolean(), nullable=False),
    sa.Column('home_lmd1', sa.Integer(), nullable=False),
    sa.Column('away_lmd1', sa.Integer(), nullable=False),
    sa.Column('lmd1_mutual', sa.Integer(), nullable=False),
    sa.Column('home_lmd2', sa.Integer(), nullable=False),
    sa.Column('away_lmd2', sa.Integer(), nullable=False),
    sa.Column('home_spg', sa.Integer(), nullable=False),
    sa.Column('away_spg', sa.Integer(), nullable=False),
    sa.Column('home_spga', sa.Integer(), nullable=False),
    sa.Column('away_spga', sa.Integer(), nullable=False),
    sa.Column('hunger_fg', sa.Integer(), nullable=False),
    sa.Column('home_fatigue', sa.Integer(), nullable=False),
    sa.Column('away_fatigue', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_philip_snat_nhl_games_id'), 'philip_snat_nhl_games', ['id'], unique=False)
    op.create_index(op.f('ix_philip_snat_nhl_games_nhl_id'), 'philip_snat_nhl_games', ['nhl_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_philip_snat_nhl_games_nhl_id'), table_name='philip_snat_nhl_games')
    op.drop_index(op.f('ix_philip_snat_nhl_games_id'), table_name='philip_snat_nhl_games')
    op.drop_table('philip_snat_nhl_games')
    # ### end Alembic commands ###
