"""cascade_delete_bet_event_on_coupon

Revision ID: 896c05fb1371
Revises: 60eca98a44be
Create Date: 2026-02-21 13:06:56.776130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896c05fb1371'
down_revision = '60eca98a44be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bet_events_on_coupons_bet_event_id_fkey', 'bet_events_on_coupons', type_='foreignkey')
    op.create_foreign_key(None, 'bet_events_on_coupons', 'bet_events', ['bet_event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bet_events_on_coupons', type_='foreignkey')
    op.create_foreign_key('bet_events_on_coupons_bet_event_id_fkey', 'bet_events_on_coupons', 'bet_events', ['bet_event_id'], ['id'])
    # ### end Alembic commands ###
