"""add_bet_event_table

Revision ID: 946f0fa2ecb8
Revises: f476d268cdfc
Create Date: 2025-10-07 20:20:45.744142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946f0fa2ecb8'
down_revision = 'f476d268cdfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sports_id'), 'sports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sports_id'), table_name='sports')
    op.drop_table('sports')
    # ### end Alembic commands ###
