"""add game table

Revision ID: a67cdf66fca9
Revises: 681992e31d79
Create Date: 2025-10-12 19:50:34.280636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a67cdf66fca9'
down_revision = '681992e31d79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.add_column('bet_events', sa.Column('game_id', sa.Integer(), nullable=False))
    op.drop_constraint('bet_events_league_id_fkey', 'bet_events', type_='foreignkey')
    op.drop_constraint('bet_events_sport_id_fkey', 'bet_events', type_='foreignkey')
    op.create_foreign_key(None, 'bet_events', 'games', ['game_id'], ['id'])
    op.drop_column('bet_events', 'away_team')
    op.drop_column('bet_events', 'league_id')
    op.drop_column('bet_events', 'home_team')
    op.drop_column('bet_events', 'sport_id')
    op.drop_column('bet_events', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_events', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('bet_events', sa.Column('sport_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bet_events', sa.Column('home_team', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('bet_events', sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bet_events', sa.Column('away_team', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bet_events', type_='foreignkey')
    op.create_foreign_key('bet_events_sport_id_fkey', 'bet_events', 'sports', ['sport_id'], ['id'])
    op.create_foreign_key('bet_events_league_id_fkey', 'bet_events', 'leagues', ['league_id'], ['id'])
    op.drop_column('bet_events', 'game_id')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
