"""cascade_delete_bet_recommendation_bet_event

Revision ID: bcd892d0d6cf
Revises: 896c05fb1371
Create Date: 2026-02-21 13:12:58.087034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd892d0d6cf'
down_revision = '896c05fb1371'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bet_recommendations_bet_event_id_fkey', 'bet_recommendations', type_='foreignkey')
    op.create_foreign_key(None, 'bet_recommendations', 'bet_events', ['bet_event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bet_recommendations', type_='foreignkey')
    op.create_foreign_key('bet_recommendations_bet_event_id_fkey', 'bet_recommendations', 'bet_events', ['bet_event_id'], ['id'])
    # ### end Alembic commands ###
