"""add_unique_constraint_user_tipster_follow

Revision ID: c005cdcd35c7
Revises: d22447bedd59
Create Date: 2026-02-12 15:29:06.100646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c005cdcd35c7'
down_revision = 'd22447bedd59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_tipster_follow', 'user_tipster_follows', ['user_id', 'tipster_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_tipster_follow', 'user_tipster_follows', type_='unique')
    # ### end Alembic commands ###
