"""add_bet_event_table

Revision ID: c73c9b99a587
Revises: 5095d12c33a7
Create Date: 2025-10-12 12:52:34.136856

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c73c9b99a587"
down_revision = "5095d12c33a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("leagues", sa.Column("download", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("leagues", "download")
    # ### end Alembic commands ###
