"""add_bet_event_table

Revision ID: dd7689c32a79
Revises: 946f0fa2ecb8
Create Date: 2025-10-07 20:21:22.400414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7689c32a79'
down_revision = '946f0fa2ecb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_events', sa.Column('sport_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bet_events', 'sports', ['sport_id'], ['id'])
    op.drop_column('bet_events', 'sport')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_events', sa.Column('sport', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bet_events', type_='foreignkey')
    op.drop_column('bet_events', 'sport_id')
    # ### end Alembic commands ###
