"""add_bet_event_table

Revision ID: f476d268cdfc
Revises: 2af88833a948
Create Date: 2025-10-07 20:17:22.674494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f476d268cdfc'
down_revision = '2af88833a948'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('appreciation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipsters_id'), 'tipsters', ['id'], unique=False)
    op.create_table('bet_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_event_id', sa.Integer(), nullable=False),
    sa.Column('tipster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bet_event_id'], ['bet_events.id'], ),
    sa.ForeignKeyConstraint(['tipster_id'], ['tipsters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_recommendations_id'), 'bet_recommendations', ['id'], unique=False)
    op.add_column('bet_events', sa.Column('odds', sa.Float(), nullable=False))
    op.add_column('bet_events', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.add_column('bet_events', sa.Column('sport', sa.String(), nullable=False))
    op.add_column('bet_events', sa.Column('league', sa.String(), nullable=False))
    op.add_column('bet_events', sa.Column('home_team', sa.String(), nullable=False))
    op.add_column('bet_events', sa.Column('away_team', sa.String(), nullable=False))
    op.add_column('bet_events', sa.Column('event', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet_events', 'event')
    op.drop_column('bet_events', 'away_team')
    op.drop_column('bet_events', 'home_team')
    op.drop_column('bet_events', 'league')
    op.drop_column('bet_events', 'sport')
    op.drop_column('bet_events', 'datetime')
    op.drop_column('bet_events', 'odds')
    op.drop_index(op.f('ix_bet_recommendations_id'), table_name='bet_recommendations')
    op.drop_table('bet_recommendations')
    op.drop_index(op.f('ix_tipsters_id'), table_name='tipsters')
    op.drop_table('tipsters')
    # ### end Alembic commands ###
