"""add_philip_snat_league_and_ai_model

Revision ID: f8ba46037f67
Revises: 30f256561df8
Create Date: 2026-02-24 18:39:47.246299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ba46037f67'
down_revision = '30f256561df8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('philip_snat_leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('update', sa.Boolean(), nullable=False),
    sa.Column('download', sa.Boolean(), nullable=False),
    sa.Column('predict', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_philip_snat_leagues_id'), 'philip_snat_leagues', ['id'], unique=False)
    op.create_table('philip_snat_ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('philip_snat_league_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['philip_snat_league_id'], ['philip_snat_leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_philip_snat_ai_models_id'), 'philip_snat_ai_models', ['id'], unique=False)
    op.create_index(op.f('ix_philip_snat_ai_models_philip_snat_league_id'), 'philip_snat_ai_models', ['philip_snat_league_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_philip_snat_ai_models_philip_snat_league_id'), table_name='philip_snat_ai_models')
    op.drop_index(op.f('ix_philip_snat_ai_models_id'), table_name='philip_snat_ai_models')
    op.drop_table('philip_snat_ai_models')
    op.drop_index(op.f('ix_philip_snat_leagues_id'), table_name='philip_snat_leagues')
    op.drop_table('philip_snat_leagues')
    # ### end Alembic commands ###
